// SPDX-License-Identifier: GPL-2.0-or-later

package org.dolphinemu.dolphinemu.features.xdnetplay.pbr

import java.io.InputStream
import org.json.JSONArray
import org.json.JSONObject

/**
 * Static Gen 4 game data, loaded from the bundled asset "xdnetplay/gen4data.json".
 * The Gen 3 editor does the same thing with gen3data.json
 * ([org.dolphinemu.dolphinemu.features.xdnetplay.gen3.Gen3Data]); this is the
 * Gen 4 sibling, with the same normalized-key convention so a Showdown paste
 * resolves identically in both.
 *
 * The asset is generated by tools/gen_gen4.py from PKHeX resources
 * (kwsch/PKHeX @ 757a297f1463) — see the "_provenance" object inside it.
 *
 * Schema:
 *   species:       { key: { id, name, baseStats [hp,atk,def,spe,spa,spd],
 *                           abilities [a1,a2], genderRatio, growth, types } }
 *   moves/items/abilities: { key: id }
 *   moveNames/itemNames/abilityNames: [ name ]  indexed by id
 *   natures:       { key: { id, name, plus, minus } }  plus/minus: -1 neutral,
 *                  else 0=atk 1=def 2=spe 3=spa 4=spd
 *   typeNames:     { typeId: name }
 *
 * Experience curves are deliberately NOT here: they live in the generated
 * [Gen4Growth] Kotlin table so the save-format layer stays JSON-free and
 * plain-JVM testable.
 *
 * Android lives in Gen4DataAssets.kt; this file is org.json + stdlib only.
 */
class Gen4Data private constructor(
    val species: Map<String, Species>,
    val moves: Map<String, Int>,
    val items: Map<String, Int>,
    val abilities: Map<String, Int>,
    val natures: Map<String, Nature>,
    val moveNames: List<String>,
    val itemNames: List<String>,
    val abilityNames: List<String>,
    val typeNames: Map<Int, String>
) {
    data class Species(
        val key: String,
        val name: String,
        val id: Int,
        /** hp, atk, def, spe, spa, spd — PersonalInfo4's own order. */
        val baseStats: IntArray,
        /** Ability 1 and 2; equal when the species has only one. */
        val abilities: IntArray,
        /** 0 = always male, 254 = always female, 255 = genderless,
         *  else female iff (PID and 0xFF) < ratio. */
        val genderRatio: Int,
        /** Experience curve index into [Gen4Growth.TABLES]. */
        val growth: Int,
        val types: IntArray
    )

    data class Nature(val key: String, val name: String, val id: Int, val plus: Int, val minus: Int)

    /** id -> display name, built once from the species table. */
    val speciesNames: Map<Int, String> by lazy {
        species.values.associate { it.id to it.name }
    }

    val natureNames: List<String> by lazy {
        val out = arrayOfNulls<String>(Bk4Mon.NATURE_COUNT)
        for (n in natures.values) {
            if (n.id in out.indices) {
                out[n.id] = n.name
            }
        }
        out.mapIndexed { i, n -> n ?: "Nature $i" }
    }

    // -- lookups (inputs are normalized the same way the keys were) ----------

    fun species(name: String): Species? = species[normalizeName(name)]

    fun moveId(name: String): Int? = moves[normalizeName(name)]

    fun itemId(name: String): Int? = items[normalizeName(name)]

    fun abilityId(name: String): Int? = abilities[normalizeName(name)]

    fun nature(name: String): Nature? = natures[normalizeName(name)]

    fun speciesName(id: Int): String = speciesNames[id] ?: "#$id"

    fun moveName(id: Int): String = moveNames.getOrNull(id) ?: "#$id"

    fun itemName(id: Int): String = itemNames.getOrNull(id) ?: "#$id"

    fun abilityName(id: Int): String = abilityNames.getOrNull(id) ?: "#$id"

    fun natureName(id: Int): String = natureNames.getOrNull(id) ?: "#$id"

    fun typeName(id: Int): String = typeNames[id] ?: "#$id"

    /** Total EXP at [level] for a species, via the generated Gen 4 curves. */
    fun expForLevel(species: Species, level: Int): Long =
        Gen4Growth.expFor(level, species.id)

    companion object {
        const val ASSET_PATH = "xdnetplay/gen4data.json"

        /**
         * Normalize a display name to a lookup key: lowercase, ASCII letters and
         * digits only, with the gender signs folded to f/m so "Nidoran♀" and
         * Showdown's "Nidoran-F" both land on "nidoranf".
         *
         * Matches normalize() in tools/gen_gen4.py, which produced the keys.
         */
        fun normalizeName(name: String): String {
            val sb = StringBuilder(name.length)
            for (raw in name.lowercase()) {
                val c = when (raw) {
                    '♀' -> 'f'
                    '♂' -> 'm'
                    else -> raw
                }
                if (c in 'a'..'z' || c in '0'..'9') {
                    sb.append(c)
                }
            }
            return sb.toString()
        }

        fun load(stream: InputStream): Gen4Data =
            fromJson(stream.readBytes().toString(Charsets.UTF_8))

        fun fromJson(text: String): Gen4Data {
            val root = JSONObject(text)

            val species = HashMap<String, Species>()
            val speciesObj = root.getJSONObject("species")
            for (key in speciesObj.keys()) {
                val s = speciesObj.getJSONObject(key)
                species[key] = Species(
                    key = key,
                    name = s.getString("name"),
                    id = s.getInt("id"),
                    baseStats = intArray(s.getJSONArray("baseStats")),
                    abilities = intArray(s.getJSONArray("abilities")),
                    genderRatio = s.getInt("genderRatio"),
                    growth = s.getInt("growth"),
                    types = intArray(s.getJSONArray("types"))
                )
            }

            val natures = HashMap<String, Nature>()
            val naturesObj = root.getJSONObject("natures")
            for (key in naturesObj.keys()) {
                val n = naturesObj.getJSONObject(key)
                natures[key] = Nature(
                    key = key,
                    name = n.getString("name"),
                    id = n.getInt("id"),
                    plus = n.getInt("plus"),
                    minus = n.getInt("minus")
                )
            }

            val typeNames = HashMap<Int, String>()
            val typeObj = root.optJSONObject("typeNames")
            if (typeObj != null) {
                for (key in typeObj.keys()) {
                    val id = key.toIntOrNull() ?: continue
                    typeNames[id] = typeObj.getString(key)
                }
            }

            return Gen4Data(
                species = species,
                moves = idMap(root.getJSONObject("moves")),
                items = idMap(root.getJSONObject("items")),
                abilities = idMap(root.getJSONObject("abilities")),
                natures = natures,
                moveNames = stringList(root.getJSONArray("moveNames")),
                itemNames = stringList(root.getJSONArray("itemNames")),
                abilityNames = stringList(root.getJSONArray("abilityNames")),
                typeNames = typeNames
            )
        }

        private fun intArray(arr: JSONArray): IntArray =
            IntArray(arr.length()) { arr.getInt(it) }

        private fun stringList(arr: JSONArray): List<String> =
            List(arr.length()) { arr.getString(it) }

        private fun idMap(obj: JSONObject): Map<String, Int> {
            val out = HashMap<String, Int>()
            for (key in obj.keys()) {
                out[normalizeName(key)] = obj.getInt(key)
            }
            return out
        }
    }
}
